# Copyright (c) 2009-2010 Satoshi Nakamoto
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

TARGET_PLATFORM:=i686
#TARGET_PLATFORM:=x86_64

DEPSDIR:=/mnt/mxe/usr/$(TARGET_PLATFORM)-w64-mingw32.static
HOST:=$(TARGET_PLATFORM)-w64-mingw32
INCDIR:=$(DEPSDIR)/include
LIBDIR:=$(DEPSDIR)/lib
AR:=$(TARGET_PLATFORM)-w64-mingw32.static-ar
CC:=$(TARGET_PLATFORM)-w64-mingw32.static-gcc
CXX:=$(TARGET_PLATFORM)-w64-mingw32.static-g++
RANLIB=$(TARGET_PLATFORM)-w64-mingw32.static-ranlib
STRIP=$(TARGET_PLATFORM)-w64-mingw32.static-strip

USE_UPNP:=0

INCLUDEPATHS= \
 -I"$(CURDIR)" \
 -I"$(CURDIR)"/obj \
 -I"$(INCDIR)/boost" \
 -I"$(INCDIR)/openssl/include" \
 -I"$(INCDIR)"

LIBPATHS= \
 -L"$(LIBDIR)"

LIBS= \
 -l boost_system-mt \
 -l boost_filesystem-mt \
 -l boost_program_options-mt \
 -l boost_thread_win32-mt \
 -l boost_chrono-mt \
 -l db_cxx \
 -l ssl \
 -l crypto \
 -l z

DEFS=-D_MT -DWIN32 -D_WINDOWS -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE
DEBUGFLAGS=
CFLAGS=-O3 -msse2 -w -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter $(DEBUGFLAGS) $(DEFS) $(INCLUDEPATHS)
CFLAGS+=-std=c++11 -Wno-unused-local-typedefs
LDFLAGS=-Wl,--dynamicbase -Wl,--nxcompat -static-libgcc -static-libstdc++

ifndef USE_UPNP
	override USE_UPNP = -
endif
ifneq (${USE_UPNP}, -)
	LIBPATHS += -L"$(DEPSDIR)/miniupnpc"
	LIBS += -l miniupnpc -l iphlpapi
	DEFS += -DSTATICLIB -DMINIUPNP_STATICLIB -DUSE_UPNP=$(USE_UPNP)
endif

ifndef ENABLE_WALLET
    override ENABLE_WALLET = 1
endif
ifneq (${ENABLE_WALLET}, 0)
    DEFS += -DENABLE_WALLET
endif

LIBS += -l mingwthrd -l kernel32 -l user32 -l gdi32 -l comdlg32 -l winspool -l winmm -l shell32 -l comctl32 -l ole32 -l oleaut32 -l uuid -l rpcrt4 -l advapi32 -l ws2_32 -l mswsock -l shlwapi

# TODO: make the mingw builds smarter about dependencies, like the linux/osx builds are
HEADERS = $(wildcard *.h)

OBJS= \
    obj/activemasternode.o \
    obj/addrdb.o \
    obj/addrman.o \
    obj/alert.o \
    obj/bitcoinrpc.o \
    obj/checkpoints.o \
    obj/clientversion.o \
    obj/crypter.o \
    obj/darksend.o \
    obj/db.o \
    obj/init.o \
    obj/ismine.o \
    obj/kernel.o \
    obj/key.o \
    obj/keystore.o \
    obj/miner.o \
    obj/main.o \
    obj/masternode.o \
    obj/masternodeconfig.o \
    obj/net.o \
    obj/netaddress.o \
    obj/netbase.o \
    obj/noui.o \
    obj/pbkdf2.o \
    obj/protocol.o \
    obj/random.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/rpcdarksend.o \
    obj/rpcrawtransaction.o \
    obj/scheduler.o \
    obj/script.o \
    obj/scrypt.o \
    obj/scrypt-arm.o \
    obj/scrypt-x86.o \
    obj/scrypt-x86_64.o \
    obj/spork.o \
    obj/sync.o \
    obj/threadinterrupt.o \
    obj/timedata.o \
    obj/txmempool.o \
    obj/ui_interface.o \
    obj/util.o \
    obj/utilmoneystr.o \
    obj/utilstrencodings.o \
    obj/utiltime.o \
    obj/validation.o \
    obj/wallet.o \
    obj/walletdb.o

all: neutrond.exe

LIBS += $(CURDIR)/leveldb/libleveldb.a $(CURDIR)/leveldb/libmemenv.a
DEFS += -I"$(CURDIR)/leveldb/include"
DEFS += -I"$(CURDIR)/leveldb/helpers"
OBJS += obj/txdb-leveldb.o
leveldb/libleveldb.a:
	@echo "Building LevelDB ..." && cd leveldb && CC=$(CC) CXX=$(CXX) TARGET_OS=OS_WINDOWS_CROSSCOMPILE CXXFLAGS="-I$(INCLUDEPATHS)" LDFLAGS="-L$(LIBPATHS)" $(MAKE) libleveldb.a libmemenv.a && $(RANLIB) libleveldb.a && $(RANLIB) libmemenv.a && cd ..
obj/txdb-leveldb.o: leveldb/libleveldb.a

obj/build.h: FORCE
	/bin/sh ../share/genbuild.sh obj/build.h
clientversion.cpp: obj/build.h
DEFS += -DHAVE_BUILD_INFO

obj/%.o: %.cpp $(HEADERS)
	$(CXX) -c $(CFLAGS) -o $@ $<

neutrond.exe: $(OBJS:obj/%=obj/%)
	$(CXX) $(CFLAGS) $(LDFLAGS) -o $@ $(LIBPATHS) $^ $(LIBS) -lshlwapi
	$(STRIP) neutrond.exe

obj/scrypt-x86.o: scrypt-x86.S
	$(CXX) -c $(CFLAGS) -MMD -o $@ $<

obj/scrypt-x86_64.o: scrypt-x86_64.S
	$(CXX) -c $(CFLAGS) -MMD -o $@ $<

obj/scrypt-arm.o: scrypt-arm.S
	$(CXX) -c $(xCXXFLAGS) -MMD -o $@ $<

clean:
	-rm -f obj/*.o
	-rm -f neutrond.exe
	-rm -f obj/build.h
	cd leveldb && TARGET_OS=OS_WINDOWS_CROSSCOMPILE $(MAKE) clean && cd ..

FORCE:
